export const GET_PRODUCTS="GET_PRODUCTS";
export const DELETE_PRODUCTS="DELETE_PRODUCTS";
export const ADD_PRODUCT="ADD_PRODUCT";
export const GET_SINGLE_PRODUCT="GET_SINGLE_PRODUCT";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";